name: Changelog

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Print git commit data
      run: |
        echo "Get author info"
        echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
        echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
        echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
        echo "Get committer info"
        echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
        echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
        echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
        echo "Get message info"
        echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
        echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
        echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"

    - name: Setup Git config
      env:
        CI_USER: ${{ env.GIT_COMMIT_AUTHOR_NAME }}
        CI_EMAIL: ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
      run: |
        git config user.name "$CI_USER"
        git config user.email "$CI_USER"

    - name: Fetch git info
      run: git fetch --all

    - name: Generate CHANGELOG file
      run: |
        echo "Install package"
        pip install auto-changelog
        echo "Generate changelog"
        python -m auto_changelog -u

    - name: Commit file
      run: git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

    - name: Push change
      if: env.push == 'true'
      env:
        PUSH_USER: ${{ env.GIT_COMMIT_AUTHOR_NAME }}
        PUSH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push "https://$PUSH_USER:$PUSH_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main