name: Changelog

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name:
      run: |
        echo "Install package"
        pip install auto-changelog
        echo "Generate changelog"
        python -m auto_changelog -u

    - name: Commit files
      uses: rlespinasse/git-commit-data-action@v1.x
      env:
        CI_USER: ${{ env.GIT_COMMIT_AUTHOR }}
        CI_EMAIL: ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
      run: |
        git config user.name "$CI_USER"
        git config user.email "$CI_USER"
        git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

    - name: Push changes
      if: env.push == 'true'
      env:
        CI_USER: ${{ env.GIT_COMMIT_AUTHOR }}
        CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main