name: Changelog

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name:
      run: |
        echo "Install package"
        pip install auto-changelog
        echo "Generate changelog"
        python -m auto_changelog -u

    - name: Commit files
      run: |
        git add CHANGELOG.md && git commit -m 'chore: Updated CHANGELOG.md'
        git push HEAD:main