name: Changelog2

on:
  push:
    branch:
      - 'main'

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v2.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
